[package]
name = "rust-real-e"
version = "0.1.0"
edition = "2021"

[dependencies]
dbase = "0.5.0"
duckdb = { version = "1.1.1", features = ["bundled"] }
prettytable = "0.10.0"
serde = { version = "1.0.213", features = ["derive"] }
